name: sunrise_signal
description: "Morning wood tracker app for men's health."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  table_calendar: ^3.1.2
  flutter_secure_storage: ^9.2.2
  file_picker: ^8.1.4
  fl_chart: ^0.69.1
  permission_handler: ^11.3.1
  device_info_plus: ^11.1.1
  # flutter_launcher_icons: ^0.14.1
  local_auth: ^2.3.0
  # workmanager: ^0.5.2
  intl: ^0.19.0
  flutter_local_notifications: ^19.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
#   flutter_launcher_icons: "^0.14.1"

# flutter_launcher_icons:
#   android: "ic_launcher_monochrome"
#   ios: true
#   remove_alpha_ios: true
#   image_path: "assets/icons/logo_monochrome.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
