name: Build for Android

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

jobs:
  build-regular-apk:
    name: Build regular APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            build
          key: ${{ runner.OS }}-ricochlime-ubuntu-${{ hashFiles('**/pubspec.lock') }}-${{ hashFiles('**/*.dart') }}
          restore-keys: |
            ${{ runner.OS }}-ricochlime-ubuntu-

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - run: flutter pub get

      - name: Build APK per ABI
        run: flutter build apk --split-per-abi

      - name: Move unsigned APKs
        run: |
          mkdir -p output
          mv build/app/outputs/flutter-apk/*.apk output/

      - name: List files in output directory
        run: ls -al output

      - name: Sign APKs
        uses: ilharp/sign-android-release@v1
        id: sign_app
        with:
          releaseDir: output
          signingKey: ${{ secrets.KEYSTORE_BASE64 }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename signed APKs
        id: rename_apk
        run: |
          for f in output/*.apk; do
            abi=$(basename $f | sed 's/.*-\(arm64-v8a\|armeabi-v7a\|x86_64\).*/\1/')
            apkName="Sunrise_Signal_${abi}.apk"
            mv $f output/$apkName
            echo "apkName=$apkName" >> $GITHUB_OUTPUT
          done

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sunrise_Signal
          path: output/

      - name: Upload to GitHub release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: |
            output/Sunrise_Signal_arm64-v8a.apk
            output/Sunrise_Signal_armeabi-v7a.apk
            output/Sunrise_Signal_x86_64.apk
